cargo-features = ["strip"]

[package]
name = "tes3conv"
version = "0.0.9"
authors = ["Greatness7 <Greatness7@gmail.com>"]
edition = "2018"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
strip = "symbols"

[dependencies]
clap = "*"
es3 = { path = "libs/es3", features = ["serde"] }
serde_json = "*"
