[package]
name = "tes3conv"
version = "0.1.0"
authors = ["Greatness7 <Greatness7@gmail.com>"]
edition = "2018"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"

[dependencies]
clap = { version = "4.2", features = ["derive"] }
serde_json = "1.0"

[dependencies.tes3]
git = "https://github.com/Greatness7/tes3"
branch = "dev"
default-features = false
features = ["esp", "serde"]
