cargo-features = ["strip"]

[package]
name = "tes3conv"
version = "0.0.7"
authors = ["Greatness7 <Greatness7@gmail.com>"]
edition = "2018"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
strip = "symbols"

[dependencies]
clap = "2.33.3"
es3 = { path = "libs/es3" }
serde_json = "1.0.64"
