name: build
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

  build-ubuntu:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          submodules: true

      - name: get toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: build release
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: build
          args: --release

      - name: package release
        run: tar -pczf tes3conv-ubuntu-latest.tar.gz -C ./target/release/ tes3conv

      - name: upload release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: tes3conv-ubuntu-latest.tar.gz

  build-macos:
    needs: setup
    runs-on: macos-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          submodules: true

      - name: get toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: build release
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: build
          args: --release

      - name: package release
        run: tar -pczf tes3conv-macos-latest.tar.gz -C ./target/release/ tes3conv

      - name: upload release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: tes3conv-macos-latest.tar.gz

  build-windows:
    needs: setup
    runs-on: windows-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          submodules: true

      - name: get toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: build release
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: build
          args: --release

      - name: package release
        run: tar.exe -acf tes3conv-windows-latest.zip -C ./target/release/ tes3conv.exe

      - name: upload release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: tes3conv-windows-latest.zip
